In [11]:
import pandas as pd

csv1 = pd.read_csv("C:\\Users\\XPS\\OneDrive\\Desktop\\Jupyter Notebook\\Pandas\\EV-Data.csv")
csv1

,region,category,parameter,mode,powertrain,year,unit,value
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Australia,Historical,EV sales share,Cars,EV,2011.0,percent,NaN
2,Australia,NaN,EV sales,NaN,BEV,2011.0,Vehicles,49.0
3,Australia,Historical,EV stock,Cars,BEV,2011.0,Vehicles,49.0
4,Australia,Historical,EV stock,Cars,BEV,2012.0,Vehicles,NaN
...,...,...,...,...,...,...,...,...
12649,World,Projection-STEPS,EV sales share,Cars,EV,2035.0,percent,55.0
12650,World,Projection-STEPS,EV stock share,Cars,EV,2035.0,percent,31.0
12651,World,Projection-APS,EV charging points,EV,Publicly available fast,2035.0,charging points,9400000.0
12652,World,Projection-APS,EV charging points,EV,Publicly available slow,2035.0,charging points,15000000.0
12653,World,Projection-STEPS,EV stock share,Trucks,EV,2035.0,percent,9.0

In [5]:
import pandas as pd
csv1 = pd.read_csv("C:\\Users\\XPS\\OneDrive\\Desktop\\Jupyter Notebook\\Pandas\\EV-Data.csv")

print(csv1.isnull())

       region  category  parameter   mode  powertrain   year   unit  value
0        True      True       True   True        True   True   True   True
1       False     False      False  False       False  False  False   True
2       False      True      False   True       False  False  False  False
3       False     False      False  False       False  False  False  False
4       False     False      False  False       False  False  False   True
...       ...       ...        ...    ...         ...    ...    ...    ...
12649   False     False      False  False       False  False  False  False
12650   False     False      False  False       False  False  False  False
12651   False     False      False  False       False  False  False  False
12652   False     False      False  False       False  False  False  False
12653   False     False      False  False       False  False  False  False

[12654 rows x 8 columns]

In [7]:
print(csv1.isnull().sum())

region        1
category      4
parameter     1
mode          2
powertrain    1
year          2
unit          1
value         4
dtype: int64

In [13]:
csv1.dropna()

,region,category,parameter,mode,powertrain,year,unit,value
3,Australia,Historical,EV stock,Cars,BEV,2011.0,Vehicles,4.900000e+01
6,Australia,Historical,EV sales share,Cars,EV,2012.0,percent,3.000000e-02
8,Australia,Historical,EV stock,Cars,PHEV,2012.0,Vehicles,8.000000e+01
11,Australia,Historical,EV stock,Cars,PHEV,2013.0,Vehicles,1.800000e+02
12,Australia,Historical,EV stock share,Cars,EV,2013.0,percent,4.600000e-03
...,...,...,...,...,...,...,...,...
12649,World,Projection-STEPS,EV sales share,Cars,EV,2035.0,percent,5.500000e+01
12650,World,Projection-STEPS,EV stock share,Cars,EV,2035.0,percent,3.100000e+01
12651,World,Projection-APS,EV charging points,EV,Publicly available fast,2035.0,charging points,9.400000e+06
12652,World,Projection-APS,EV charging points,EV,Publicly available slow,2035.0,charging points,1.500000e+07
12653,World,Projection-STEPS,EV stock share,Trucks,EV,2035.0,percent,9.000000e+00

In [15]:
csv1.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[12654 rows x 0 columns]

In [17]:
csv1.dropna(how="any")

,region,category,parameter,mode,powertrain,year,unit,value
3,Australia,Historical,EV stock,Cars,BEV,2011.0,Vehicles,4.900000e+01
6,Australia,Historical,EV sales share,Cars,EV,2012.0,percent,3.000000e-02
8,Australia,Historical,EV stock,Cars,PHEV,2012.0,Vehicles,8.000000e+01
11,Australia,Historical,EV stock,Cars,PHEV,2013.0,Vehicles,1.800000e+02
12,Australia,Historical,EV stock share,Cars,EV,2013.0,percent,4.600000e-03
...,...,...,...,...,...,...,...,...
12649,World,Projection-STEPS,EV sales share,Cars,EV,2035.0,percent,5.500000e+01
12650,World,Projection-STEPS,EV stock share,Cars,EV,2035.0,percent,3.100000e+01
12651,World,Projection-APS,EV charging points,EV,Publicly available fast,2035.0,charging points,9.400000e+06
12652,World,Projection-APS,EV charging points,EV,Publicly available slow,2035.0,charging points,1.500000e+07
12653,World,Projection-STEPS,EV stock share,Trucks,EV,2035.0,percent,9.000000e+00

In [29]:
csv1.dropna(subset=["year"])

,region,category,parameter,mode,powertrain,year,unit,value
3,Australia,Historical,EV stock,Cars,BEV,2011.0,Vehicles,4.900000e+01
6,Australia,Historical,EV sales share,Cars,EV,2012.0,percent,3.000000e-02
8,Australia,Historical,EV stock,Cars,PHEV,2012.0,Vehicles,8.000000e+01
11,Australia,Historical,EV stock,Cars,PHEV,2013.0,Vehicles,1.800000e+02
12,Australia,Historical,EV stock share,Cars,EV,2013.0,percent,4.600000e-03
...,...,...,...,...,...,...,...,...
12649,World,Projection-STEPS,EV sales share,Cars,EV,2035.0,percent,5.500000e+01
12650,World,Projection-STEPS,EV stock share,Cars,EV,2035.0,percent,3.100000e+01
12651,World,Projection-APS,EV charging points,EV,Publicly available fast,2035.0,charging points,9.400000e+06
12652,World,Projection-APS,EV charging points,EV,Publicly available slow,2035.0,charging points,1.500000e+07
12653,World,Projection-STEPS,EV stock share,Trucks,EV,2035.0,percent,9.000000e+00

In [31]:
csv1.dropna(inplace=True)
csv1

,region,category,parameter,mode,powertrain,year,unit,value
3,Australia,Historical,EV stock,Cars,BEV,2011.0,Vehicles,4.900000e+01
6,Australia,Historical,EV sales share,Cars,EV,2012.0,percent,3.000000e-02
8,Australia,Historical,EV stock,Cars,PHEV,2012.0,Vehicles,8.000000e+01
11,Australia,Historical,EV stock,Cars,PHEV,2013.0,Vehicles,1.800000e+02
12,Australia,Historical,EV stock share,Cars,EV,2013.0,percent,4.600000e-03
...,...,...,...,...,...,...,...,...
12649,World,Projection-STEPS,EV sales share,Cars,EV,2035.0,percent,5.500000e+01
12650,World,Projection-STEPS,EV stock share,Cars,EV,2035.0,percent,3.100000e+01
12651,World,Projection-APS,EV charging points,EV,Publicly available fast,2035.0,charging points,9.400000e+06
12652,World,Projection-APS,EV charging points,EV,Publicly available slow,2035.0,charging points,1.500000e+07
12653,World,Projection-STEPS,EV stock share,Trucks,EV,2035.0,percent,9.000000e+00