In [5]:
import pandas as pd

data = pd.read_csv("EV-Data.csv")
data

,region,category,parameter,mode,powertrain,year,unit,value
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Australia,Historical,EV sales share,Cars,EV,2011.0,percent,NaN
2,Australia,NaN,EV sales,NaN,BEV,2011.0,Vehicles,49.0
3,Australia,Historical,EV stock,Cars,BEV,2011.0,Vehicles,49.0
4,Australia,Historical,EV stock,Cars,BEV,2012.0,Vehicles,NaN
...,...,...,...,...,...,...,...,...
12649,World,Projection-STEPS,EV sales share,Cars,EV,2035.0,percent,55.0
12650,World,Projection-STEPS,EV stock share,Cars,EV,2035.0,percent,31.0
12651,World,Projection-APS,EV charging points,EV,Publicly available fast,2035.0,charging points,9400000.0
12652,World,Projection-APS,EV charging points,EV,Publicly available slow,2035.0,charging points,15000000.0
12653,World,Projection-STEPS,EV stock share,Trucks,EV,2035.0,percent,9.0

In [7]:
print(data.duplicated())

0        False
1        False
2        False
3        False
4        False
         ...
12649    False
12650    False
12651    False
12652    False
12653    False
Length: 12654, dtype: bool

In [11]:
print(data["parameter"].duplicated().sum())

12645

In [15]:
print(data.drop_duplicates("category"))

         region          category           parameter   mode powertrain  \
0           NaN               NaN                 NaN    NaN        NaN
1     Australia        Historical      EV sales share   Cars         EV
1400      China  Projection-STEPS  Electricity demand  Buses         EV
1404      China    Projection-APS      EV sales share  Buses         EV

        year     unit    value
0        NaN      NaN      NaN
1     2011.0  percent      NaN
1400  2020.0      GWh  15000.0
1404  2020.0  percent     66.0